import { Inter } from "next/font/google";
import "./globals.css"; // Certifique-se de que o caminho está correto

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>  
      <title>Notas</title>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
